/**
 * Article bodies for the Insights blog. Kept in one place so the
 * CMS migration (Sanity or similar) has a single source to replace.
 * Voice: precise, confident, quietly assertive — no hype adjectives.
 */
export const ARTICLE_BODIES: Record<string, string[]> = {
  "why-bangladeshi-brands-lose": [
    "Walk through any market in Dhaka — Gulshan or New Market, it makes no difference — and count how many brands you actually remember an hour later. The honest answer for most people is one, maybe two. Not because the products were bad. Because everything looked and sounded like everything else.",
    "We call this the camouflage trap, and it has four patterns. The first is borrowed identity: the founder picks a color, a font, and a name that feels safe because a bigger competitor already validated it. The second is feature shouting — leading every communication with specs and prices, the two things a customer can compare against you instantly. The third is random acts of marketing: a boosted post here, a discount there, no strategy connecting them. The fourth is the silence problem — the brand publishes nothing for months, then wonders why nobody remembers it.",
    "Here is the uncomfortable truth: in a crowded category, being 10% better than competitors gets you nothing. Being 10% different gets you everything. The brands that win Bangladeshi categories — think of the telecom giants or the top education brands — win on distinction first, quality second. Not because quality doesn't matter, but because nobody gets to experience your quality if they never notice you exist.",
    "The pattern we see in every brand that escapes the trap is the same: they choose a position and defend it. One school decides it is the strict one, and every parent in the neighborhood knows it within two admission seasons. One cloud kitchen decides it is the spicy one, and the city's group chats do its marketing for free. Distinction compounds. Camouflage compounds too — into invisibility.",
    "If you take one thing from this piece, take this: audit your last ten social posts, your packaging, and your sales pitch. If a competitor could paste their logo over any of it without anyone noticing, you don't have a brand yet. You have a placeholder. The good news — the market rewards the first brand in a category brave enough to be unmistakable.",
  ],
  "positioning-is-a-territory": [
    "Every marketing course teaches positioning as a sentence: 'For [audience], [brand] is the [category] that [benefit].' It fits nicely on a slide. It does almost nothing in a market. Sentences don't hold ground. Systems do.",
    "The difference between a tagline and a moat is time and defense. A tagline is a claim you make once. A position is a claim you defend every single day — in what you sell, what you refuse to sell, how you answer the phone, what you post, and what you say no to. When we repositioned a boutique real estate developer around 'own your corner of the city,' the line was the smallest part of the work. The work was cutting three projects that didn't fit the claim, retraining every salesperson to stop leading with square footage, and rebuilding the listing photography around the lives people would live, not the walls they would buy.",
    "Positioning changes your competitive instincts. When a competitor undercuts you, you don't match their price — because price is a border dispute, and border disputes exhaust everyone. You reinforce what they can't copy: your claim, delivered consistently for years, compounding into what economists call share of mind and what we simply call being the name people say first.",
    "Three Dhaka case studies, three different categories, one identical mechanic. A school claimed rigor and stopped apologizing for it — enrollment rose 42% in one season. A fashion marketplace claimed speed and rebuilt its entire checkout — conversion nearly doubled. A cloud kitchen claimed attitude and let the feed do the talking — twelve thousand orders in month one. None of them were the cheapest. All of them were the clearest.",
    "So before you write your positioning statement, draw your map: what do we claim, what do we refuse, and what will we defend for five years even when it costs us short-term revenue? If you can't answer the second and third questions, the first one is just a sentence.",
  ],
  "motion-is-advantage": [
    "On screens, the brands that move get noticed first. This isn't a design opinion — the human eye is wired to prioritize motion over stillness; it's how the visual cortex allocates attention. Yet most brand identities in Bangladesh are built entirely for static placements: a logo, a color, a font — frozen.",
    "Motion identity is the discipline of designing how your brand moves. Not adding animation to your logo — that's decoration — but defining the physics of your brand: how fast it enters, how it settles, what its energy signature is. A luxury brand should glide. A sports brand should snap. An agency that claims precision should have an interface that moves with intent. When the motion language matches the positioning, the brand feels true at every touchpoint.",
    "The feed economy made this non-negotiable. Your audience now meets brands in environments where everything moves — reels, stories, animated ads. A static brand in a moving feed reads as asleep. The data is consistent: animated ad creative outperforms static on both recall and click-through in most Bangladeshi verticals we've tested, and the gap widens every year.",
    "But there's a discipline to it. Motion without rules becomes a circus, and a circus is as forgettable as a statue. Our rule is simple: every movement must have a reason traceable to the brand's strategy. Our own site opens with deliberate stillness before a single amber line cuts through — that's not a style choice; it's the positioning, executed in time instead of space.",
    "If your brand guidelines document doesn't have a motion section, you're competing in a moving market with a still weapon. Start small: define your brand's default speed, its entrance energy, and its resting behavior. Three decisions. That's enough to change how alive your brand feels.",
  ],
  "dhaka-market-trends-2026": [
    "Every category in Bangladesh is heading toward consolidation. The era of a dozen undifferentiated players surviving side by side is ending — rising media costs, maturing consumers, and professional competition are crowding the middle. By the end of 2026, most categories will have one brand that owns the category conversation and a long tail fighting for scraps.",
    "The first trend: category kings are being crowned early. In e-commerce, fashion, and food delivery, we're already seeing winner-take-most dynamics. The brands that invested in distinct identity and consistent presence through the noisy years are pulling away from brands that competed on discounts. Discounting builds no memory. Distinction does.",
    "The second trend: the video-first consumer is now the default consumer. Bangladesh's data costs keep falling and short-form video consumption keeps climbing across every demographic — including the older, wealthier segments that used to be reachable through print and outdoor. Brands that haven't built a video capability — in-house or through partners — are becoming invisible to their own buyers.",
    "The third trend: authenticity has become a price of entry, not a differentiator. Consumers have learned to smell manufactured trust. The brands winning now show their floors, their founders, their failures. The polish era is ending; the proof era is here. This is great news for genuinely good businesses and terrible news for brands that were all wrapper.",
    "Our advice to every founder reading this: pick your position now, while the middle still exists. In two years, the categories will have their kings, and taking a crown from a sitting king costs ten times what claiming an open one costs today. The market is about to get a lot less crowded at the top. Make sure your brand is in the running.",
  ],
  "first-position-startup": [
    "You launched the product. It works. People pay for it. And your brand is still the logo your cousin made in Canva at 2am the night before launch. This is the most common gap we see in Bangladeshi startups — not a quality gap, an identity gap. And the fix takes less time than you think.",
    "The First Position sprint is our four-week identity system for startups. Here's what's in it — and more importantly, what's deliberately not. Week one is positioning only: one page, three questions — who is it for, what do we claim, what do we refuse. Most startups skip this and it costs them everything downstream. Week two is verbal identity: the words you use, the words you ban, the one sentence every team member can repeat in their sleep.",
    "Week three is visual identity — but compressed. Not a 90-page brand book. A logo system, two typefaces, one accent color, and rules for photography. Enough to be consistent everywhere you show up. Week four is the rollout kit: social templates, pitch deck, and a one-pager for investors. Done. You can safely skip the mascot, the custom typeface, and the 40-page guidelines nobody will read.",
    "What you cannot skip: the positioning. We've watched startups spend eight months and a fortune on a beautiful identity wrapped around a fuzzy claim — and watched cheaper competitors with sharper claims eat their market. Identity amplifies positioning. It doesn't replace it.",
    "If you're pre-Series A and deciding between a full rebrand and growth spend, do the sprint. Four weeks, one team, one system. Then put every taka into being seen. That's the whole game in the early market: be unmistakable, be everywhere your buyer looks, and don't burn cash on decoration.",
  ],
  "performance-branding": [
    "There's a war inside most marketing teams, and it sounds like this: 'Brand is a luxury — we need conversions this month.' Versus: 'Performance is a treadmill — stop it and everything stops.' Both are right, which is exactly why the war never ends. The resolution isn't a truce. It's a unified strategy: performance branding.",
    "Performance branding means every performance campaign reinforces the brand's position, and every brand asset is built to convert. The discount ad carries the same voice as the brand film. The brand film has a call to action. Nothing ships that isn't simultaneously buying attention now and building memory for later.",
    "Mechanically, we run it in three layers. Layer one is the position layer — always-on brand content that keeps the claim visible and searchable. Layer two is the demand layer — performance campaigns targeted at active buyers, built in the brand's voice instead of generic urgency. Layer three is the memory layer — retargeting that tells the brand story to people who didn't convert the first time, instead of just showing them the same product again with a bigger discount.",
    "The results compound in a specific order: performance lifts first, cost per acquisition drops second, and brand search volume — the metric that proves memory is being built — rises third, usually 60-90 days in. Teams that quit at week six never see the third effect, and conclude branding doesn't work. It does. It's just slower than a discount.",
    "The one-line summary we give every client: performance rents attention; branding owns it. Run both, in one voice, on one strategy — and the market starts learning your name whether or not you're paying for the introduction.",
  ],
};
